#!/bin/bash
if [ "$(id -u)" != "0" ]; then
echo "This script must be run as root. Rerunning with sudo."
sudo "$0" "$@"
exit $?
fi
MODULES="$(lsmod | sed -nE 's/^\s*(.*hci_pci)\s+.*$/\1/p')"
echo "$MODULES" | xargs -I{} rmmod {}
echo "$MODULES" | xargs -I{} modprobe {}
